### PR TITLE
Added support for multi platform docker images

### PR DESCRIPTION
**Pull request by pmorelli92**
Aims to solve #104 

@natenho I am not entirely sure if this works because I have no idea how to test this.
I basically followed the instructions from here: https://github.com/docker/build-push-action/blob/master/docs/advanced/multi-platform.md

### CODE REVIEW

**Comment by pmorelli92** [comment]
Hi @natenho any hope you can have a look at this?

**Comment by natenho** [comment]
Hi @pmorelli92, I'll have a look into this by the end of the week!

**Comment by natenho** [comment]
@pmorelli92 looks ok, although I noticed that the "echo" step is blank. I'll merge anyway to check if the images are correctly published to dockerhub, but I'm going to need your help to check if it worked, ok?

image

**Comment by pmorelli92** [comment]
@natenho Thanks a lot for this. An entire team is able to work better now 👏 

Screenshot 2022-11-09 at 15 28 00

Screenshot 2022-11-09 at 15 30 56

**Pull request merged**
