### PR TITLE
ci: update main release to run on pull requests

### LINKED ISSUE #94: Include pull request workflow
**Is your feature request related to a problem? Please describe.**

Currently, the `main-release.yml` is not run on the pull request so there is not an automatic check before merging to the main branch.

**Describe the solution you'd like**

Modify the current `main-release.yml` to perform a dry execution (not publish NuGet, not publish docker image) but build and test the .NET projects and build the container.

**Describe alternatives you've considered**

Current scenario.

**Additional context**

### PR DESCRIPTION
**Pull request by gomete**
Closes #94

### CODE REVIEW

**Review by natenho — APPROVED** [review]

**Comment by natenho** [comment]
@gomete thanks for this one! 
Could you please verify the failed check?

**Comment by gomete** [comment]
Sure, seems that we cannot publish the unit tests results from another repo pull request. I'm going to remove that step.

**Comment by gomete** [comment]
Seems that it is possible granting `checks: write` permission to the job: <https://github.com/dorny/test-reporter/issues/149>

**Comment by gomete** [comment]
Hi @natenho, just removing the step that requires `write` permission and going with `read` permission only.

**Comment by gomete** [comment]
Hi @natenho, did you have the chance to review this?

**Pull request merged**
