### PR TITLE
feat: allow using mockaco on aspnet core apps

### LINKED ISSUE #88: Use Mockaco in an ASP.NET Core app
Hi there,

I have been checking Mockaco to mock HTTP requests and I love how it works and how templating is conceived but it would be nice to extend it using the ASP.NET capabilities. Have you ever considered dividing Mockaco in the current dotnet tool and a package that can be used in an ASP.NET Core app in a similar way [YARP did it](https://microsoft.github.io/reverse-proxy/articles/getting-started.html#update-startup)?

Some of the advantages:

- Users will be able to add middlewares to the mocking pipeline (e.g, if they want to log the request or whatever).
- Users can add other controllers or endpoints can be added and manage the priority.
- Users can use all the packages that ASP.NET Core also has like OpenTelemetry, prometheus-net.AspNetCore, etc.
- Users can use their custom authentication/authorization.

I did a quick probe of concept and it is almost prepared (as it is using middlewares and the built-in dependency injection) to use it this way and it can be reused in the dotnet tool. **If you are interested I can do the changes in a fork and submit a PR to discuss it**.

So it could be used (in a similar way to YARP), registering the services and configuration:

```csharp
    public static IServiceCollection AddCustomMockaco(this IServiceCollection services) =>
		services
	        .AddMockaco()
    		.LoadFromFolder("Mocks")
			.Services;
```

And then mapping the mock endpoints with the `IApplicationBuilder`:

**Without any customization in the pipeline**:

```csharp
    public static IEndpointConventionBuilder MapCustomMockaco(this IEndpointRouteBuilder app) =>
        app.MapMockaco();
```

**Customizing the pipeline**:

```csharp
    public static IEndpointConventionBuilder MapCustomMockaco(this IEndpointRouteBuilder app) =>
        app.MapMockaco(mockingPipeline =>
        {
            mockingPipeline.UseMiddleware<LoggingMiddleware>();
            mockingPipeline.UseMiddleware<AuditingMiddleware>();
        });
```

### PR DESCRIPTION
**Pull request by gomete**
Closes #88 

Hi @natenho!

These are the changes that I did to use Mockaco in an ASP.NET Core app:

- We have created a new package `Mockaco.AspNetCore` with the main logic, extracting the dependency injection and configuration of endpoints.
- We have added a new way of changing the configuration that fits better with an ASP.NET Core app but maintaining the previous way of configuring it.
- We have migrated it to .NET 6 as it is LTS.
- We have moved the VerifyController to use `.MapGet` to avoid the conditional `MapWhen` and avoid making it public, so it is not part of the API of the package.
- We have added the package `Microsoft.CodeAnalysis.PublicApiAnalyzers` so it is easy to identify which parts of the package are public and to detect breaking changes.
- We have made internal all the classes that potentially can be internal. The rest of them are public because of `Microsoft.CodeAnalysis.CSharp.Scripting`.
- It is compatible with the current standalone `Mockaco`. We have added some Postman tests to ensure that at least the examples are still working as expected. The Postman tests `test/_postman/Mockaco.postman_collection.json` and the script `checkBuild.ps1` can be removed once you tested the change. We only used them to ensure that the build, the unit tests and the Docker build will work.
- We have tested adding a controller and an additional `MapGet` to the existing ASP.NET Core using Mockaco to check that it is using the controller/`MapGet` instead of using Mockaco. In case there is no match in the existing controllers, it is handled by Mockaco.

### CODE REVIEW

**Comment by natenho** [comment]
Well that is a big PR!! It's indeed an awesome feature!
Thank you for your time, I'm glad that you are interested to contribute to the project! I'll be reviewing everything here soon ;-)

**Comment by gomete** [comment]
Hi @natenho, did you have the chance to review this?

**Comment by natenho** [comment]
Hi @gomete, I apologize the delay. A few days ago I had to fix a bug and I was working on integrating this PR https://github.com/natenho/Mockaco/pull/87, where I noticed some points that needs some improvement before merging. My plan is to merge #87 and your PRs would be the next ones. I would appreciate if you could integrate the current master branch into your code until there.

Anyway, I did not forget your PRs, hang tight! ;)

**Comment by gomete** [comment]
Hi @natenho, thanks for the quick response! I will solve the conflicts this afternoon.

**Pull request merged**
